version: '3.8'

services:
  db:
    image: postgres:15
    container_name: marketplace_db
    restart: always
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    image: jvpascale/marketplace-backend:v2
    container_name: marketplace_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marketplace
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    image: leaolu/frontendbd1:v1
    container_name: marketplace_frontend
    restart: always
    ports:
      - "3000:80" 
    depends_on:
      - app 
